### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by mebjas** [mebjas/mod_csrfprotector#1]
- [x] Add required function defination to global listing [link to LOC](https://github.com/mebjas/mod_csrfprotector/blob/master/apache%202.2/src/mod_csrfprotector.c#L105)
- [x] Currently every request is being processes limit it to certain formats, we need not parse header for an image
- [x] Better random token generation function
- [x] Output filter doesn't take care of target at bucket boundary case ( `....<bo] [dy>...`), ie `<bo` in one bucket `dy>` in another
- [x] Cookie is not yet sent to client, need to implement code to modify output header for cookie
- [x] Remove useless codes
- [x] implement logging in case of failed validation
- [x] Add support for `text/xhtml`
- [x] Add environment variable, for php to know, mod_csrfp is functional
